# Generated by Django 3.0.7 on 2020-06-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=18)),
                ('hostname', models.CharField(max_length=14)),
                ('loopback', models.CharField(max_length=15)),
                ('macaddress', models.CharField(max_length=17)),
                ('is_deleted', models.IntegerField(default=False)),
            ],
            options={
                'db_table': 'funny',
            },
        ),
    ]
